[test] this commit will fail.

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -1,4 +1,4 @@
-name: Build App
+name: Build
 
 on:
   pull_request:
@@ -15,6 +15,11 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
+        
+      - name: Intentional Failure
+        run: |
+          echo "This step will intentionally fail."
+          exit 1
 
       - name: Set up Python
         uses: actions/setup-python@v5
